/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDto {
    username?: string;
    password?: string;
    personId?: number;
    firstName?: string;
    lastName?: string;
    docNumber?: string;
    email?: string;
    phone?: string;
    userId?: number;
    isOwner?: boolean;
}